# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 17:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('category', models.CharField(choices=[('A', 'Мотоцикл'), ('B', 'Легковая'), ('C', 'Грузовая'), ('D', 'Автобус')], max_length=1, verbose_name='Категория')),
                ('date_create', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'транспортное средство',
                'ordering': ('date_create',),
                'verbose_name_plural': 'транспортные средства',
            },
        ),
    ]
