# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-13 17:18
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
            ],
            options={
                'verbose_name_plural': 'процедуры',
                'verbose_name': 'процедура',
            },
        ),
        migrations.CreateModel(
            name='ProcedureExecution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_create', models.DateField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('datetime_create', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время создания')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedure_executions', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('procedure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executions', to='workflow.Procedure', verbose_name='Процедура')),
            ],
            options={
                'verbose_name_plural': 'выполненные процедуры',
                'ordering': ('-datetime_create',),
                'verbose_name': 'выполненная процедура',
            },
        ),
        migrations.AlterUniqueTogether(
            name='procedureexecution',
            unique_together=set([('employee', 'procedure', 'date_create')]),
        ),
    ]
