# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-14 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(null=True)),
                ('url', models.URLField(blank=True)),
                ('date_create', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
